# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/services/password_reset/password_reset.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='app/services/password_reset/password_reset.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n0app/services/password_reset/password_reset.proto\"\x14\n\x12PasswordResetEmpty\"#\n\x12\x43reateTokenRequest\x12\r\n\x05\x65mail\x18\x01 \x02(\t\"$\n\x13\x43reateTokenResponse\x12\r\n\x05token\x18\x01 \x02(\t\"7\n\x14ResetPasswordRequest\x12\r\n\x05token\x18\x01 \x02(\t\x12\x10\n\x08password\x18\x02 \x02(\t2\x88\x01\n\rPasswordReset\x12\x39\n\x0c\x63reate_token\x12\x13.CreateTokenRequest\x1a\x14.CreateTokenResponse\x12<\n\x0ereset_password\x12\x15.ResetPasswordRequest\x1a\x13.PasswordResetEmpty'
)




_PASSWORDRESETEMPTY = _descriptor.Descriptor(
  name='PasswordResetEmpty',
  full_name='PasswordResetEmpty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=72,
)


_CREATETOKENREQUEST = _descriptor.Descriptor(
  name='CreateTokenRequest',
  full_name='CreateTokenRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='email', full_name='CreateTokenRequest.email', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=109,
)


_CREATETOKENRESPONSE = _descriptor.Descriptor(
  name='CreateTokenResponse',
  full_name='CreateTokenResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='CreateTokenResponse.token', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=147,
)


_RESETPASSWORDREQUEST = _descriptor.Descriptor(
  name='ResetPasswordRequest',
  full_name='ResetPasswordRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='ResetPasswordRequest.token', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='ResetPasswordRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=204,
)

DESCRIPTOR.message_types_by_name['PasswordResetEmpty'] = _PASSWORDRESETEMPTY
DESCRIPTOR.message_types_by_name['CreateTokenRequest'] = _CREATETOKENREQUEST
DESCRIPTOR.message_types_by_name['CreateTokenResponse'] = _CREATETOKENRESPONSE
DESCRIPTOR.message_types_by_name['ResetPasswordRequest'] = _RESETPASSWORDREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PasswordResetEmpty = _reflection.GeneratedProtocolMessageType('PasswordResetEmpty', (_message.Message,), {
  'DESCRIPTOR' : _PASSWORDRESETEMPTY,
  '__module__' : 'app.services.password_reset.password_reset_pb2'
  # @@protoc_insertion_point(class_scope:PasswordResetEmpty)
  })
_sym_db.RegisterMessage(PasswordResetEmpty)

CreateTokenRequest = _reflection.GeneratedProtocolMessageType('CreateTokenRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATETOKENREQUEST,
  '__module__' : 'app.services.password_reset.password_reset_pb2'
  # @@protoc_insertion_point(class_scope:CreateTokenRequest)
  })
_sym_db.RegisterMessage(CreateTokenRequest)

CreateTokenResponse = _reflection.GeneratedProtocolMessageType('CreateTokenResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATETOKENRESPONSE,
  '__module__' : 'app.services.password_reset.password_reset_pb2'
  # @@protoc_insertion_point(class_scope:CreateTokenResponse)
  })
_sym_db.RegisterMessage(CreateTokenResponse)

ResetPasswordRequest = _reflection.GeneratedProtocolMessageType('ResetPasswordRequest', (_message.Message,), {
  'DESCRIPTOR' : _RESETPASSWORDREQUEST,
  '__module__' : 'app.services.password_reset.password_reset_pb2'
  # @@protoc_insertion_point(class_scope:ResetPasswordRequest)
  })
_sym_db.RegisterMessage(ResetPasswordRequest)



_PASSWORDRESET = _descriptor.ServiceDescriptor(
  name='PasswordReset',
  full_name='PasswordReset',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=207,
  serialized_end=343,
  methods=[
  _descriptor.MethodDescriptor(
    name='create_token',
    full_name='PasswordReset.create_token',
    index=0,
    containing_service=None,
    input_type=_CREATETOKENREQUEST,
    output_type=_CREATETOKENRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='reset_password',
    full_name='PasswordReset.reset_password',
    index=1,
    containing_service=None,
    input_type=_RESETPASSWORDREQUEST,
    output_type=_PASSWORDRESETEMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PASSWORDRESET)

DESCRIPTOR.services_by_name['PasswordReset'] = _PASSWORDRESET

# @@protoc_insertion_point(module_scope)
