# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app.protos import password_reset_pb2 as app_dot_services_dot_password__reset_dot_password__reset__pb2


class PasswordResetStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.create_token = channel.unary_unary(
                '/PasswordReset/create_token',
                request_serializer=app_dot_services_dot_password__reset_dot_password__reset__pb2.CreateTokenRequest.SerializeToString,
                response_deserializer=app_dot_services_dot_password__reset_dot_password__reset__pb2.CreateTokenResponse.FromString,
                )
        self.reset_password = channel.unary_unary(
                '/PasswordReset/reset_password',
                request_serializer=app_dot_services_dot_password__reset_dot_password__reset__pb2.ResetPasswordRequest.SerializeToString,
                response_deserializer=app_dot_services_dot_password__reset_dot_password__reset__pb2.PasswordResetEmpty.FromString,
                )


class PasswordResetServicer(object):
    """Missing associated documentation comment in .proto file."""

    def create_token(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def reset_password(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PasswordResetServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'create_token': grpc.unary_unary_rpc_method_handler(
                    servicer.create_token,
                    request_deserializer=app_dot_services_dot_password__reset_dot_password__reset__pb2.CreateTokenRequest.FromString,
                    response_serializer=app_dot_services_dot_password__reset_dot_password__reset__pb2.CreateTokenResponse.SerializeToString,
            ),
            'reset_password': grpc.unary_unary_rpc_method_handler(
                    servicer.reset_password,
                    request_deserializer=app_dot_services_dot_password__reset_dot_password__reset__pb2.ResetPasswordRequest.FromString,
                    response_serializer=app_dot_services_dot_password__reset_dot_password__reset__pb2.PasswordResetEmpty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PasswordReset', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PasswordReset(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def create_token(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PasswordReset/create_token',
            app_dot_services_dot_password__reset_dot_password__reset__pb2.CreateTokenRequest.SerializeToString,
            app_dot_services_dot_password__reset_dot_password__reset__pb2.CreateTokenResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def reset_password(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PasswordReset/reset_password',
            app_dot_services_dot_password__reset_dot_password__reset__pb2.ResetPasswordRequest.SerializeToString,
            app_dot_services_dot_password__reset_dot_password__reset__pb2.PasswordResetEmpty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
